### ISSUE TITLE
How to save?

### ISSUE THREAD

**Issue by Researcher33** [arifkhan-silicornya/Vanilla_Javascript_password_Generator#1]
Hello, how can we collect each generated password in a file as a document.

**Comment by arif-khan-shanto** [comment]
you can follow this link:  https://github.com/arifkhan-silicornya/multiple_password_generator

preview: https://arifkhan-silicornya.github.io/multiple_password_generator/

**Comment by Researcher33** [comment]
Thanks. I think I explained it wrong. When I publish the codes on a website, how do we ensure that all the passwords created by the people who visit my website are collected in a single file. For example: Mr. Arif came to my website, created a password and the system saved the password. I saw this from the system too.

**Comment by arif-khan-shanto** [comment]
For this, you must use a database to save a password and who created this.  You can't do this using only javascript. 
You have to use a backend technology like node, express, PHP, laravel, django, asp or jsp. and you can use any database.

**Comment by Researcher33** [comment]
I did some research on what you said and came to a conclusion. Thank you so much.

**Comment by arif-khan-shanto** [comment]
oh!, great and wc
